[package]
name = "c-comp4learn"
version = "0.1.0"
authors = ["Liam R Mitchell <liam.mitchell@uleth.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"
lazy_static = "1.2.0"
